package com.nullpointercats.sys.adopta.user.dto.response

/**
 * DTO used to send authentication information back to the client
 * after a successful login operation.
 *
 * This response contains the session token generated by the system,
 * which the client must include in future authenticated requests.
 */
data class LoginResponse(

    /**
     * Session token generated after successful authentication.
     * This token identifies the user's active session and is
     * typically used for authorization in subsequent requests.
     */
    val token: String

)