spring.application.name=adopta
spring.datasource.url=jdbc:postgresql://${URL_DB}
spring.datasource.username=${USER_DB}
spring.datasource.password=${PASSWORD_DB}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USER}
spring.mail.password=${GMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

external.api.dog.url=https://api.thedogapi.com/v1
external.api.cat.url=https://api.thecatapi.com/v1
external.api.dog.key=${DOG_API_KEY}
external.api.cat.key=${CAT_API_KEY}